refactor: update section "Children pass-through" to use a functional component
rubenmarcus/guiareact.org pull request #28
Opened 2021-11-23 21:31 UTC by artursilveiradev

![Screenshot from 2021-11-23 18-30-19](https://user-images.githubusercontent.com/93391443/143132328-ad4ad189-406e-400c-8ad6-20a1fcffabfb.png)

2021-11-24 17:44 UTC, MurilloCunha commented
Oi, fiquei na dúvida se não poderia ser algo do tipo também :

```
function SomeContextProvider({ children }) {
    return (
        <MyContext.Provider value={ initialValue }>
              // como retornamos children?
        </MyContext.Provider>
    )
}

```
o que acha?

2021-11-25 00:47 UTC, artursilveiradev commented
> Oi, fiquei na dúvida se não poderia ser algo do tipo também :
> 
> ```
> function SomeContextProvider({ children }) {
>     return (
>         <MyContext.Provider value={ initialValue }>
>               // como retornamos children?
>         </MyContext.Provider>
>     )
> }
> ```
> 
> o que acha?

Fala Murillo, beleza? Então, no exemplo em inglês ele fala em context, porém aparentemente não faz o uso do mesmo. Acho que pra esse exemplo podemos manter essa estrutura, até porque ainda não temos uma sessão no site que aborde os hooks e a Context API. Futuramente, quando essas sessões forem adicionadas, acho que podemos pensar em um exemplo usando o Context.Provider como você falou.

2021-11-25 12:17 UTC, taisesoares commented
Olá @MurilloCunha tudo bem? Estou contribuindo com o conteúdo da contextApi e um de reducer já que no exemplo irei usa-lo. Logo envio a PR para aprovação :) Ai podemos atualizar esse conteúdo quem sabe :)

2022-07-09 23:35 UTC, rubenmarcus requested changes
@artursilveiradev  obrigado pelo update dos functional components

2022-07-09 23:35 UTC, rubenmarcus commented on documentation/DOC-HOME.md
> +function SomeContextProvider({ children }) {
melhor seria usar arrow function.

```

const SomeContextProvider ({ children }) { 

getChildContext = () => { some: "context" }

// como retornamos children?

    return (
      <SomeContextProvider.Provider value={state}>
        {children}
      </SomeContextProvider.Provider>
    )
```

2022-07-09 23:35 UTC, rubenmarcus commented on documentation/DOC-HOME.md
> +return React.Children.only(children);
Isso aqui e esse exemplo não fazem sentido mais. Preciso rever essa documentação

2022-07-09 23:37 UTC, rubenmarcus commented
obrigado pela discussão galera!!!

Eu vou rever todo o conteudo porque tem muita coisa antiga, e vou rever a navegação que está ruim também.

@artursilveiradev @taisesoares  @MurilloCunha  obrigado pela discussão! vou fechar o P/R e vou fazer uma nova versão desse site! Obrigado!

2022-07-09 23:37 UTC, closed without merging